[project]
name = "self-improving-efms-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "mediapy>=1.2.6",
    "numpy>=1.26.0,<2.1.0",
    "dm-env>=1.6",
    "moviepy>=2.2.1",
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "h5py>=3.10.0",
    "wandb>=0.16.0",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
